Merged PocketMine-Docker repo into the main repo I don't think it ever made sense for these to be separated. It just gets in the way of testing. Not least the fact that the Docker image can't be built from an untagged commit...

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,31 +1,28 @@
 # Build stage for compilation. Build tools like g++ will not be copied into the final stage to reduce image size.
-FROM ubuntu:22.04
-ARG PMMP_TAG
-ARG COMPILE_SH_ARGS="-f -g"
-ARG PMMP_REPO=pmmp/PocketMine-MP
+FROM ubuntu:22.04 AS build
+ARG COMPILE_SH_ARGS="-f -g -P5"
+ARG GIT_HASH=""
 
-RUN test ! -z ${PMMP_TAG} || (echo "Missing build-arg PMMP_TAG" && false)
+RUN test ! -z ${GIT_HASH} || (echo "Missing build-arg GIT_HASH" && false)
 
 RUN apt-get update && apt-get install --no-install-recommends -y curl ca-certificates build-essential m4 gzip bzip2 bison git cmake autoconf automake pkg-config libtool libtool-bin re2c
 
-RUN mkdir /build
-WORKDIR /build
-RUN git clone https://github.com/${PMMP_REPO}.git -b ${PMMP_TAG} --recursive .
-WORKDIR /build/build/php
-RUN ./compile.sh -t linux64 -j ${THREADS:-$(grep -E ^processor /proc/cpuinfo | wc -l)} ${COMPILE_SH_ARGS} -P $(echo ${PMMP_TAG} | cut -d "." -f1)
-RUN ln -s /build/build/php/bin/php7/bin/php /usr/bin/php
+RUN mkdir /pocketmine
+COPY . /pocketmine
+WORKDIR /pocketmine/build/php
+RUN ./compile.sh -t linux64 -j ${THREADS:-$(grep -E ^processor /proc/cpuinfo | wc -l)} ${COMPILE_SH_ARGS}
+RUN ln -s /pocketmine/build/php/bin/php7/bin/php /usr/bin/php
 
-WORKDIR /build
+WORKDIR /pocketmine
 RUN curl -L https://getcomposer.org/installer | php
 RUN mv composer.phar /usr/bin/composer
 
 RUN composer install --classmap-authoritative --no-dev --prefer-source
-RUN if test -d build/preprocessor; then php build/preprocessor/PreProcessor.php --path=src --multisize; else echo "Skipping preprocessor step (preprocessor not found)"; fi
-RUN php $(test -d vendor/pocketmine/bedrock-data && echo -n vendor/pocketmine/bedrock-data || echo -n src/pocketmine/resources/vanilla)/.minify_json.php
+RUN php vendor/pocketmine/bedrock-data/.minify_json.php
 
 RUN php -dphar.readonly=0 build/server-phar.php --git $(git rev-parse HEAD)
-# Just to make sure DevTools didn't false-positive-exit
-RUN test -f /build/PocketMine-MP.phar
+# Just to make sure the build script didn't false-positive-exit
+RUN test -f /pocketmine/build/PocketMine-MP.phar
 
 FROM ubuntu:22.04
 LABEL maintainer="PMMP Team <team@pmmp.io>"
@@ -36,11 +33,11 @@ RUN groupadd -g 1000 pocketmine
 RUN useradd -r -d /pocketmine -p "" -u 1000 -m -g pocketmine pocketmine
 
 WORKDIR /pocketmine
-COPY --from=0 /build/build/php/bin/php7 /usr/php
+COPY --from=build /pocketmine/build/php/bin/php7 /usr/php
 RUN grep -q '^extension_dir' /usr/php/bin/php.ini && \
 	sed -ibak "s{^extension_dir=.*{extension_dir=\"$(find /usr/php -name *debug-zts*)\"{" /usr/php/bin/php.ini || echo "extension_dir=\"$(find /usr/php -name *debug-zts*)\"" >> /usr/php/bin/php.ini
 RUN ln -s /usr/php/bin/php /usr/bin/php
-COPY --from=0 /build/PocketMine-MP.phar PocketMine-MP.phar
+COPY --from=build /pocketmine/PocketMine-MP.phar PocketMine-MP.phar
 ADD start.sh /usr/bin/start-pocketmine
 
 RUN mkdir /plugins /data
